### ISSUE TITLE
[BUG] Save estimator hdf5 with method as DAR

### ISSUE THREAD

**Issue by alexrockhill** [pactools/pactools#31]
See minimally reproducible example:

```py
import numpy as np
import matplotlib.pyplot as plt

from pactools import Comodulogram
from pactools import simulate_pac
from pactools.dar_model import DAR, extract_driver
fs = 200.  # Hz
high_fq = 50.0  # Hz
low_fq = 5.0  # Hz
low_fq_width = 1.0  # Hz

n_points = 10000
noise_level = 0.4

signal = simulate_pac(n_points=n_points, fs=fs, high_fq=high_fq, low_fq=low_fq,
                      low_fq_width=low_fq_width, noise_level=noise_level,
                      random_state=0)
dar = DAR(ordar=20, ordriv=2, criterion='bic')
estimator = Comodulogram(fs=fs, low_fq_range=low_fq_range,
                             low_fq_width=low_fq_width, method=dar,
                             progress_bar=False)
estimator.fit(signal)
estimator.save('test.hdf5')

```

Gives
```pytb
/Users/alexrockhill/software/anaconda3/envs/swannlab/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alexrockhill/software/pactools/pactools/comodulogram.py", line 591, in save
    slash='replace')
  File "/Users/alexrockhill/software/anaconda3/envs/swannlab/lib/python3.7/site-packages/mne-0.21.dev0-py3.7.egg/mne/externals/h5io/_h5io.py", line 115, in write_hdf5
    use_json=use_json)
  File "/Users/alexrockhill/software/anaconda3/envs/swannlab/lib/python3.7/site-packages/mne-0.21.dev0-py3.7.egg/mne/externals/h5io/_h5io.py", line 151, in _triage_write
    where + '["%s"]' % key, cleanup_data=cleanup_data, slash=slash)
  File "/Users/alexrockhill/software/anaconda3/envs/swannlab/lib/python3.7/site-packages/mne-0.21.dev0-py3.7.egg/mne/externals/h5io/_h5io.py", line 232, in _triage_write
    raise TypeError(err_str)
TypeError: unsupported type <class 'pactools.dar_model.dar.DAR'> (in <class 'dict'>["method"]) 
```

**Comment by TomDLT** [comment]
Indeed, saving DAR models with hdf5 is not supported, see #14.
I won't have much time to fix this though, so any help is welcome !

**Comment by alexrockhill** [comment]
Ah should have seen that, okay maybe I will do this later.
